name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.label.name == 'release'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release workflow is run!"
